### ISSUE TITLE
Add Transfer Metadata Form

### ISSUE THREAD

**Issue by rhernand3z** [NYPL/nypl-recap-admin#3]
Add the transfer metadata form to spec:
https://projects.invisionapp.com/share/AJFAS22HE#/screens/274558125

Barcodes: 14 numerical digits
bibRecordNumber: @thisisstephenbetts can you confirm the validation rules on this field?
protectCGD: true false boolean (defaults to false)

**Comment by rhernand3z** [comment]
As per @thisisstephenbetts the rule is:

starts with the letter `b` followed by 8 numerical digits followed by one character which could be a numerical digit or the letter `x`

Regex:
`/^b\d{8}[\dx]$/`

**Comment by kfriedman** [comment]
Just curious, where did you derive this rule?

I know our partners have letters in their barcodes, for example.

**Comment by thisisstephenbetts** [comment]
This was from Kate.

The definition is roughly here, though it doesn't say it _has_ to be 8
digits — that I confirmed with her (cannot update the doc myself)
https://docs.google.com/document/d/1DTRAV-DQI05P-HbzNl3RH8q32b8e_YvpdAJapyEafoA/edit#heading=h.fwz3yabpl9he

Stephen.

**Comment by rhernand3z** [comment]
Closed by #5
